name: thesis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - adjusttext=1.3.0=pyhd8ed1ab_0
  - anyio=4.10.0=pyhe01879c_0
  - anytree=2.13.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py39hb1cfd32_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - atk-1.0=2.38.0=h4bec284_2
  - attrs=25.3.0=pyh71513ae_0
  - autograd=1.8.0=pyhd8ed1ab_0
  - aws-c-auth=0.9.3=hdff831d_0
  - aws-c-cal=0.9.13=hea39f9f_1
  - aws-c-common=0.12.6=h8616949_0
  - aws-c-compression=0.3.1=h901532c_9
  - aws-c-event-stream=0.5.7=ha05da6a_1
  - aws-c-http=0.10.7=h924c446_5
  - aws-c-io=0.23.3=hf559bb5_5
  - aws-c-mqtt=0.13.3=ha72ff4e_11
  - aws-c-s3=0.11.3=he30762a_1
  - aws-c-sdkutils=0.2.4=h901532c_4
  - aws-checksums=0.2.7=h901532c_5
  - aws-crt-cpp=0.35.4=h7484968_0
  - aws-sdk-cpp=1.11.606=h386ebac_10
  - azure-core-cpp=1.16.1=he2a98a9_0
  - azure-identity-cpp=1.13.2=h0e8e1c8_1
  - azure-storage-blobs-cpp=12.16.0=ha4e89a6_0
  - azure-storage-common-cpp=12.12.0=h2a5eb39_0
  - azure-storage-files-datalake-cpp=12.14.0=h7f37a48_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beartype=0.21.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - biopython=1.85=py39h80efdc8_1
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.0.9=py39h7a8716b_8
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h7656bdc_1
  - certifi=2025.8.3=py39hecd8cb5_0
  - cffi=1.17.1=py39h8ddeee6_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.0=py39h0d3c867_2
  - cramjam=2.11.0=py39h848e47f_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py39h6581403_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fastparquet=2024.11.0=py39h86e9f7f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py39h2753485_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h694c41f_0
  - fribidi=1.0.16=h8616949_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdk-pixbuf=2.44.4=h07555a4_0
  - gensim=4.3.3=py39h64cd7fd_0
  - gflags=2.2.2=hac325c4_1005
  - glog=0.7.1=h2790a97_0
  - graphite2=1.3.14=h21dd04a_2
  - graphviz=9.0.0=hee74176_1
  - graspologic=3.3.0=pyhd8ed1ab_0
  - graspologic-native=1.2.5=py39h98fa8a5_0
  - gtk2=2.24.33=he806959_8
  - gts=0.7.6=h53e17e3_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=12.3.2=h8b84c26_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hyppo=0.5.2=pyhd8ed1ab_0
  - icu=78.2=h14c5de8_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.18.1=pyh707e725_3
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py39h6e9494a_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py39h0d8d0ca_0
  - krb5=1.21.3=h37d8d59_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.18=h90db99b_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250512.1=cxx17_hfc00f1c_0
  - libarrow=21.0.0=h57e2ed6_16_cpu
  - libarrow-acero=21.0.0=h37ec541_16_cpu
  - libarrow-compute=21.0.0=h09bde0c_16_cpu
  - libarrow-dataset=21.0.0=h37ec541_16_cpu
  - libarrow-substrait=21.0.0=h3b119cc_16_cpu
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.18.0=h9348e2b_0
  - libcxx=21.1.8=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=hd1f9c09_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_15
  - libgd=2.3.3=hb2c11ec_12
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - libglib=2.86.3=hf241ffe_0
  - libgoogle-cloud=2.39.0=hed66dea_0
  - libgoogle-cloud-storage=2.39.0=h8ac052b_0
  - libgrpc=1.73.1=h451496d_1
  - libhwloc=2.12.2=default_h273dbb7_1000
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.11.0=5_h859234e_openblas
  - libllvm14=14.0.6=hc8e404f_4
  - liblzma=5.8.2=h11316ed_0
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libopentelemetry-cpp=1.21.0=h7d3f41d_1
  - libopentelemetry-cpp-headers=1.21.0=h694c41f_1
  - libparquet=21.0.0=ha52c220_16_cpu
  - libpng=1.6.54=h07817ec_0
  - libprotobuf=6.31.1=hcc66ac3_4
  - libre2-11=2025.11.05=h554ac88_0
  - librsvg=2.60.0=h2da6fc3_0
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.2=hb99441e_0
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.22.0=h687e942_1
  - libtiff=4.7.1=ha0a348c_1
  - libutf8proc=2.11.3=hc282952_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.15.1=h24ca049_1
  - libxml2-16=2.15.1=he456531_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - llvmlite=0.43.0=py39h164c851_1
  - lz4-c=1.10.0=h240833e_1
  - markupsafe=3.0.2=py39hd18e689_1
  - matplotlib=3.9.4=py39h6e9494a_0
  - matplotlib-base=3.9.4=py39hda06d36_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=1.31.0=py39hecd8cb5_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=h06076ce_1
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.60.0=py39h90d9702_0
  - numpy=1.26.4=py39h28c39a1_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.6.0=h230baf5_0
  - orc=2.2.2=h3073fbf_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.1=py39hb4b21fd_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h6ef8af8_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.47=h13923f0_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py39h1fda9f2_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=ha059160_1
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.0.1=py39he13d532_0
  - pot=0.9.5=py39hb7d32d6_0
  - prometheus-cpp=1.3.0=h7802330_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39h80efdc8_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py39h6e9494a_0
  - pyarrow-core=21.0.0=py39h0f88efd_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pygraphviz=1.11=py39hf025324_2
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyobjc-core=11.0=py39h4881f39_0
  - pyobjc-framework-cocoa=11.0=py39h4881f39_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=h8a7f3fd_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39hd18e689_2
  - pyzmq=27.0.2=py39h7cc8fb6_0
  - qhull=2020.2=h3c5361c_5
  - re2=2025.11.05=h7df6414_0
  - readline=8.3=h68b038d_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.0=py39h4b192f4_0
  - scikit-learn=1.6.1=py39he8fe7b2_0
  - scipy=1.13.1=py39h038d4f4_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smart_open=7.3.0.post1=pyhe01879c_0
  - snappy=1.2.2=h01f5ddf_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py39hbbd48fb_0
  - tbb=2022.3.0=h06b67a2_2
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h7142dee_3
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py39hb1cfd32_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - umap-learn=0.5.9.post2=py39h6e9494a_0
  - unicodedata2=16.0.0=py39h80efdc8_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py39hb1cfd32_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.23.0=py39hb1cfd32_3
  - zstd=1.5.7=h3eecb57_6
  - pip:
    - choreographer==1.2.1
    - fvec==0.0.1
    - iniconfig==2.1.0
    - kaleido==0.2.1
    - logistro==2.0.1
    - orjson==3.11.5
    - pluggy==1.6.0
    - pytest==8.4.2
    - pytest-timeout==2.4.0
    - simplejson==3.20.2
prefix: /Users/ssm47/opt/anaconda3/envs/thesis_env
